version: '3.8'

services:
  auth-service:
    build: ./backend/auth_service
    ports:
      - "5001:5001"

  user-service:
    build: ./backend/user_service
    ports:
      - "5002:5002"

  exercise-service:
    build: ./backend/exercise_service
    ports:
      - "5003:5003"

  api-gateway:
    build: ./backend/api_gateway
    ports:
      - "5000:5000"
    depends_on:
      - auth-service
      - user-service
      - exercise-service

  frontend:
    build: ./frontend # Assuming you have a Dockerfile for the frontend
    ports:
      - "80:80" # You can use a different port if necessary
    depends_on:
      - api-gateway
